// PlansElos Tests
// Generated by @create-ngrx-state generator

// State Tests
export * from './plansElos.state.spec';

// Actions Tests
export * from './plansElos.actions.spec';

// Reducer Tests
export * from './plansElos.reducer.spec';

// Selectors Tests
export * from './plansElos.selectors.spec';

// Effects Tests
export * from './plansElos.effects.spec';

// Facade Service Tests
export * from './plansElos-facade.service.spec';
