import {
  Component,
  OnInit,
  Output,
  EventEmitter,
  Input,
  ViewChild,
  ElementRef,
  AfterViewInit,
} from '@angular/core';
import { CommonModule } from '@angular/common';

import { Chessboard, BOARD_TYPE, ChessboardConfig } from 'cm-chessboard';
import { Markers } from 'cm-chessboard/src/extensions/markers/Markers.js';
import { Chess, Move } from 'chess.js';

@Component({
  selector: 'lib-chess960-board',
  imports: [CommonModule],
  templateUrl: './chess960-board.html',
  styleUrl: './chess960-board.css',
})
export class Chess960Board implements OnInit, AfterViewInit {
  @ViewChild('boardContainer') boardContainer!: ElementRef;

  @Output() moveMade = new EventEmitter<Move>();

  @Input() set boardConfig(config: ChessboardConfig) {
    this.config = { ...this.config, ...config };
    if (this.board) {
      this.setPosition(this.config.position as string);
    } else if (this.boardContainer) {
      this.buildBoard();
    }
  }

  private config: ChessboardConfig = {
    coordinates: false,
    responsive: true,
    position: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1',
    assetsUrl: 'assets/cm-chessboard/assets/',
    style: {
      cssClass: 'chessboard-js',
      showCoordinates: true,
      pieces: {
        file: 'pieces/standard.svg',
      },
    },
    extensions: [{ class: Markers }],
  };

  private board: any = null;
  private chess = new Chess();
  private startFen = '';

  ngOnInit() {}

  ngAfterViewInit() {
    if (!this.board) {
      this.buildBoard();
    }
  }

  async buildBoard() {
    if (!this.boardContainer) return;

    this.board = await new Chessboard(
      this.boardContainer.nativeElement as HTMLElement,
      this.config
    );
    try {
      this.chess.load(this.config.position as string);
    } catch (e) {}
    this.startFen = this.config.position as string;

    this.board.enableMoveInput((event: any) => {
      switch (event.type) {
        case 'moveInputStarted':
          return true;
        case 'validateMoveInput':
          return this.validateMove(
            event.squareFrom,
            event.squareTo,
            event.piece
          );
        case 'moveInputCanceled':
          break;
      }
      return true;
    });
  }

  private validateMove(source: string, target: string, piece: string): boolean {
    const isWhite = piece.startsWith('w');
    const colorCode = isWhite ? 'w' : 'b';
    const kingPiece = colorCode + 'k';
    const rookPiece = colorCode + 'r';

    // Basic logic for chess960 castling on the UI side.
    // In Chess960, castling is done by dragging the King onto the Rook.
    let move: Move | null = null;
    let isCastling = false;

    // Check if dragging King onto friendly Rook
    const targetPieceObj = this.chess.get(target as any);
    if (
      piece === kingPiece &&
      targetPieceObj &&
      targetPieceObj.type === 'r' &&
      targetPieceObj.color === colorCode
    ) {
      isCastling = true;
      // In chess.js, O-O / O-O-O are usually generated by specifying target square of the King's final destination
      // Standard castling destinations: G1 / C1 (white) or G8 / C8 (black)
      let kingDestination = '';
      if (isWhite) {
        // King is currently moving to a rook's square
        // If rook is on H file side (K-side), king goes to g1
        const targetCol = target.charCodeAt(0);
        if (targetCol > source.charCodeAt(0)) {
          kingDestination = 'g1';
        } else {
          kingDestination = 'c1';
        }
      } else {
        const targetCol = target.charCodeAt(0);
        if (targetCol > source.charCodeAt(0)) {
          kingDestination = 'g8';
        } else {
          kingDestination = 'c8';
        }
      }

      try {
        move = this.chess.move({ from: source, to: kingDestination });
      } catch (e) {
        return false;
      }
    } else {
      try {
        move = this.chess.move({ from: source, to: target });
      } catch (e) {
        // Handle promotion automatically to Queen for simplicity
        try {
          move = this.chess.move({ from: source, to: target, promotion: 'q' });
        } catch (e2) {
          return false;
        }
      }
    }

    if (move) {
      setTimeout(() => {
        this.board.setPosition(this.chess.fen(), true);
        this.moveMade.emit(move!);
      }, 100);
      return true;
    }
    return false;
  }

  public setPosition(position: string) {
    this.config = { ...this.config, position };
    try {
      this.chess.load(position);
    } catch (e) {
      /* fallback to standard if invalid fen */
    }

    if (this.board) {
      this.board.setPosition(position, true);
    }
  }

  public changeOrientation(orientation: 'w' | 'b') {
    if (this.board) {
      this.board.setOrientation(orientation);
    }
  }

  getOrientation(): 'w' | 'b' {
    return this.board ? this.board.getOrientation() : 'w';
  }

  public isBoardReady(): boolean {
    return this.board !== null;
  }
}
